server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-peer1:8761/eureka/, http://discovery-service-peer2:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: http://user-service:8080
          predicates:
          - Path=/api/user/auth
        - id: registration
          uri: http://user-service:8080
          predicates:
          - Path=/api/user/registration,/api/user/confirmation**
        - id: user-service
          uri: http://user-service:8080
          predicates:
          - Path=/api/user/**
          filters: 
          - TokenValidatingFilter
        - id: course-service
          uri: http://course-service:8080
          predicates:
          - Path=/api/course/**
          filters: 
          - TokenValidatingFilter
        - id: task-service
          uri: http://task-service:8080
          predicates:
          - Path=/api/task/**
          filters: 
          - TokenValidatingFilter
        - id: feedback-service
          uri: http://feedback-service:8080
          predicates:
          - Path=/api/feedback/**
          filters: 
          - TokenValidatingFilter
        - id: filemanagement-service
          uri: http://filemanagement-service:8080
          predicates:
          - Path=/api/filemanagement/**
          filters: 
          - TokenValidatingFilter
